project_identifier: wire-launch
base_path: src
preserve_hierarchy: true

files:
  -
    source: '/pages/en/**/*.html'
    translation: '/pages/%locale%/**/%original_file_name%'
    type: 'html'
    update_option: 'update_as_unapproved'

  -
    source: '/partials/en/**/*.html'
    translation: '/partials/%locale%/**/%original_file_name%'
    type: 'html'
    update_option: 'update_as_unapproved'
